### ISSUE TITLE
Constants in show_pen.m

### ISSUE THREAD

**Issue by Symaxion** [szcom/rnnlib#15]
I am trying to adapt this program to run with my own sample sets. While doing so, I found that the outputs of the neural network don't correspond directly to relative coordinates, but instead need to have some constants multiplied and added to them, labelled `muXY` and `devXY` in `show_pen.m`.

Tweaking these constants, I have not found what their exact significance is, but only that if the ratio between them changes too much, the output becomes distorted.

I assume that these constants are dependent on the dataset. I have not found any references to them in the source code, nor in the original paper published by Alex Graves. What are these constants and how would I calculate them for my own dataset?

**Comment by szcom** [comment]
these are the mean and std deviation of the dataset. since data set is normalized one must apply reverse to the net's outputs.
use mean and std dev from your dataset in place of these constants

**Comment by Symaxion** [comment]
Thank you for taking the time to answer my question. This was my initial guess as well, but I was a bit surprised because the `x`,`y` coordinates in the dataset all have values in the order of 2,000, while the average used in the script was only around 200. I couldn't find any reference to this normalization process in the paper either. Thanks again!

**Comment by szcom** [comment]
x,y are 'delta' coded ( x is a delta b/w 2 consequent ts) thus their magnitude is less of that in the dataset.
